language: java
sudo: required
jdk:
- oraclejdk8
- openjdk8
after_success:
- ./gradlew jacocoTestReport coveralls
deploy:
  provider: script
  script: ./gradlew clean build bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  on:
    tags: true
    jdk: openjdk8
